/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Vista.ListaEstudiantes;
import Vista.JPanelHome;
import Vista.JPanelHome;
import Vista.ListaEstudiantes;
import Vista.SolicitudAlumno;
import java.awt.BorderLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author diego
 */
public class Inicio extends javax.swing.JFrame {
    
    
    public Inicio() {
        initComponents();
        
        JPanelHome pl = new JPanelHome();
        showPanelHome(pl);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        Panel = new javax.swing.JPanel();
        PnlSide = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        Home = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        Listas = new javax.swing.JButton();
        ListasNotas = new javax.swing.JButton();
        ListasNom = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        PnlContent = new javax.swing.JPanel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Panel.setLayout(new java.awt.BorderLayout());

        PnlSide.setBackground(new java.awt.Color(21, 25, 28));
        PnlSide.setPreferredSize(new java.awt.Dimension(80, 0));
        PnlSide.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(21, 25, 28));
        jPanel1.setPreferredSize(new java.awt.Dimension(80, 100));

        Home.setBackground(new java.awt.Color(34, 40, 44));
        Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_home_20px_2.png"))); // NOI18N
        Home.setToolTipText("Inicio");
        Home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Home.setPreferredSize(new java.awt.Dimension(40, 40));
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(Home, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Home, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );

        PnlSide.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, -1, -1));

        jPanel2.setBackground(new java.awt.Color(21, 25, 28));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.setPreferredSize(new java.awt.Dimension(80, 250));
        jPanel2.setRequestFocusEnabled(false);

        Listas.setBackground(new java.awt.Color(34, 40, 44));
        Listas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_square_brackets_20px.png"))); // NOI18N
        Listas.setToolTipText("Listas de Números");
        Listas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Listas.setPreferredSize(new java.awt.Dimension(40, 40));
        Listas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListasActionPerformed(evt);
            }
        });

        ListasNotas.setBackground(new java.awt.Color(34, 40, 44));
        ListasNotas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-matrix-24.png"))); // NOI18N
        ListasNotas.setToolTipText("Listas Bidimensionales");
        ListasNotas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ListasNotas.setPreferredSize(new java.awt.Dimension(40, 40));
        ListasNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListasNotasActionPerformed(evt);
            }
        });

        ListasNom.setBackground(new java.awt.Color(34, 40, 44));
        ListasNom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_location_off_20px_2.png"))); // NOI18N
        ListasNom.setToolTipText("Listas de Nombres");
        ListasNom.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ListasNom.setPreferredSize(new java.awt.Dimension(40, 40));
        ListasNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListasNomActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ListasNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ListasNotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Listas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ListasNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ListasNotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Listas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        PnlSide.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, -1, -1));

        Salir.setBackground(new java.awt.Color(34, 40, 44));
        Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_logout_20px.png"))); // NOI18N
        Salir.setToolTipText("Salir");
        Salir.setBorder(null);
        Salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Salir.setPreferredSize(new java.awt.Dimension(40, 40));
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        PnlSide.add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 365, -1, -1));

        Panel.add(PnlSide, java.awt.BorderLayout.WEST);

        PnlContent.setBackground(new java.awt.Color(34, 40, 44));

        javax.swing.GroupLayout PnlContentLayout = new javax.swing.GroupLayout(PnlContent);
        PnlContent.setLayout(PnlContentLayout);
        PnlContentLayout.setHorizontalGroup(
            PnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 967, Short.MAX_VALUE)
        );
        PnlContentLayout.setVerticalGroup(
            PnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 685, Short.MAX_VALUE)
        );

        Panel.add(PnlContent, java.awt.BorderLayout.CENTER);

        getContentPane().add(Panel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        // TODO add your handling code here:
        JPanelHome pl = new JPanelHome();
        showPanelHome(pl);
    }//GEN-LAST:event_HomeActionPerformed

    private void ListasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListasActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_ListasActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(null, "¿Salir de la aplicación?", "Salir", JOptionPane.YES_NO_OPTION) == 0){
            System.exit(0);
        }
        
    }//GEN-LAST:event_SalirActionPerformed

    private void ListasNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListasNotasActionPerformed
        SolicitudAlumno n = new SolicitudAlumno();
        n.setVisible(true);
        
    }//GEN-LAST:event_ListasNotasActionPerformed

    private void ListasNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListasNomActionPerformed
        ListaEstudiantes p = new ListaEstudiantes();
        p.setVisible(true);
    }//GEN-LAST:event_ListasNomActionPerformed
    private void showPanelHome(JPanelHome p){
        p.setSize(725, 600);
        p.setLocation(0, 0);
        
        PnlContent.removeAll();
        PnlContent.add(p, BorderLayout.CENTER);
        PnlContent.revalidate();
        PnlContent.repaint();
    }
    
    
    private void showListaNotas(ListaEstudiantes n1){
        n1.setSize(725, 600);
        n1.setLocation(0, 0);
        PnlContent.removeAll();
        PnlContent.add(n1, BorderLayout.CENTER);
        PnlContent.revalidate();
        PnlContent.repaint();
    }
   
    private void showFormulario(SolicitudAlumno p1){
        
        p1.setSize(725, 600);
        p1.setLocation(0, 0);
        PnlContent.removeAll();
        PnlContent.add(p1, BorderLayout.CENTER);
        PnlContent.revalidate();
        PnlContent.repaint();
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Home;
    private javax.swing.JButton Listas;
    private javax.swing.JButton ListasNom;
    private javax.swing.JButton ListasNotas;
    private javax.swing.JPanel Panel;
    private javax.swing.JPanel PnlContent;
    private javax.swing.JPanel PnlSide;
    private javax.swing.JButton Salir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
